version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run test-ci
  deploy-job:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/repo
    steps:
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "a3:28:2e:ce:3b:36:a8:08:63:f9:c1:a6:31:3e:36:0c"
      - run:
          name: Deploy master to Heroku
          command: |
            git push git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            heroku run python manage.py deploy
            heroku restart
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master


